Pin tox to 4.8.0 to troubleshoot CI/CD failures running the tests
Error from CI/CD:

   Run docker exec
   ROOT: HandledError| provided environments not found in configuration file: ['tests-aviator-graphics-cov-linux']

Suspected to be due to tox 4,.9.0 and https://github.com/tox-dev/tox/pull/3089
Error: Process completed with exit code 254.