Update tox.ini after tox 4.8.0 upgrade
Running tests broke after upgrading to tox 4.8.0 because of https://github.com/tox-dev/tox/pull/3089 which requires the environments to be explicitly specified in the config file:

Run docker exec \
  docker exec \
    --workdir /home/stk/pystk \
    stk-python3.8 /bin/bash -c \
    "export COVERAGE_FILE=aviator && tox -e tests-aviator-graphics-cov-linux"
  shell: /usr/bin/bash -e {0}
  env:
    MAIN_PYTHON_VERSION: 3.10
    LIBRARY_NAME: ansys-stk-core
    LIBRARY_NAMESPACE: ansys.stk.core
    DOCUMENTATION_CNAME: stk.docs.pyansys.com
    STK_DOCKER_IMAGE: ansys/stk:latest-centos7
    PYSTK_DIR: /home/stk/pystk
    LICENSE_SERVER_PORT: 1055
    STK_PYTHON_IMAGE: ansys/stk:latest-centos7-python3.8
    STK_CONTAINER: stk-python3.8
ROOT: HandledError| provided environments not found in configuration file: ['tests-aviator-graphics-cov-linux']
Error: Process completed with exit code 254.